### ISSUE TITLE
Can't build with caddy 2.6.4

### ISSUE THREAD

**Issue by ont** [lolPants/caddy-requestid#4]
# Problem
Panic during building caddy with `xcaddy`.
```
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc000abf6c8?, 0xc0005cb5a8?}, {0xc000118660?, 0xc0012ab5c0?}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc0000d8100, {0xb313d0, 0xc00002a068}, {0xc000cb4e00, 0x1, 0x1})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc0000d8100, {0xb313d0, 0xc00002a068}, {0xc0017da660?, 0x1?, 0x472485?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0x105
cmd/go/internal/modget.runGet({0xb313d0, 0xc00002a068}, 0xc000028498?, {0xc000024220, 0x2, 0x2})
	/usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x45e
main.invoke(0xe2cfc0, {0xc0000241f0, 0x5, 0x5})
	/usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
2023/02/16 20:06:51 [FATAL] exit status 2
```

# How to reproduce
Run builder container with:
`docker run -it --rm caddy:2.6.4-builder sh`

Then inside builder container:
`xcaddy build --with github.com/lolPants/caddy-requestid`

# Possible solution
Upgrade dependencies as was mentioned in https://github.com/golang/go/issues/56494#issuecomment-1425022660

**Comment by luludotdev** [comment]
should be fixed by 806a48f2adf377be8bea9aa2f869949399432938
